version: 2.1
orbs:
  go: circleci/go@2.2.3

jobs:
  build_and_test: # this can be any name you choose
    parameters:
      go-version:
        type: string
    executor:
      name: go/default # Use the default executor from the orb
      tag: << parameters.go-version >>
    steps:
      - checkout
      - go/mod-download
      - go/gotestsum
      - store_test_results:
          path: .
workflows:
  main:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              go-version: ["1.18", "1.23"]
