version: 2.1
orbs:
  go: circleci/go@2.2.3

jobs:
  build_and_test: # this can be any name you choose
    executor:
      name: go/default # Use the default executor from the orb
      tag: "1.23" # Specify a version tag
    steps:
      - checkout
      - go/mod-download
      - go/gotestsum
      - store_test_results:
          path: .
workflows:
  main:
    jobs:
      - build_and_test
